### ISSUE TITLE
"brew install risingwave" Failed

### ISSUE THREAD

**Issue by WZRPW** [risingwavelabs/homebrew-risingwave#10]
OS: macOS Big Sur version 11.6
Xcode: 13.2.1
installed the latest command line tool.

###############################################################
error[E0425]: cannot find function `consume_budget` in module `tokio::task`
   --> src/storage/src/hummock/sstable/forward_sstable_iterator.rs:248:22
    |
248 |         tokio::task::consume_budget().await;
    |                      ^^^^^^^^^^^^^^ not found in `tokio::task`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `risingwave_storage` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `risingwave_cmd_all v0.19.0 (/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/src/cmd_all)`, intermediate artifacts can be found at `/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/target`

###
full log:
##############
 user@ABCDE  ~/   sudo xcode-select --install
xcode-select: note: install requested for command line developer tools
 user@ABCDE ~/  brew install risingwave
Running `brew update --auto-update`...
Installing from the API is now the default behaviour!
You can save space and time by running:
  brew untap homebrew/core
  brew untap homebrew/cask
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
==> New Casks
screen-studio

You have 12 outdated formulae installed.

==> Fetching risingwavelabs/risingwave/risingwave
==> Downloading https://github.com/risingwavelabs/risingwave/archive/refs/tags/v0.19.0.tar.gz
Already downloaded: /Users/admin/Library/Caches/Homebrew/downloads/9c68b337755f6c4201d85a4e5b8f81b66237488113eafe2e141211ec4f8a83c2--risingwave-0.19.0.tar.gz
==> Installing risingwave from risingwavelabs/risingwave
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.2.1.

==> /usr/local/opt/rustup-init/bin/rustup-init -qy --no-modify-path --default-toolchain none
==> cargo install --bin risingwave --features rw-static-link src/cmd_all
Last 15 lines from /Users/admin/Library/Logs/Homebrew/risingwave/02.cargo:
   Compiling risingwave_rpc_client v0.19.0 (/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/src/rpc_client)
   Compiling risingwave_backup v0.19.0 (/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/src/storage/backup)
   Compiling risingwave_common_service v0.19.0 (/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/src/common/common_service)
   Compiling risingwave_connector v0.19.0 (/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/src/connector)
   Compiling risingwave_storage v0.19.0 (/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/src/storage)
error[E0425]: cannot find function `consume_budget` in module `tokio::task`
   --> src/storage/src/hummock/sstable/forward_sstable_iterator.rs:248:22
    |
248 |         tokio::task::consume_budget().await;
    |                      ^^^^^^^^^^^^^^ not found in `tokio::task`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `risingwave_storage` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `risingwave_cmd_all v0.19.0 (/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/src/cmd_all)`, intermediate artifacts can be found at `/private/tmp/risingwave-20230708-45694-1hmce0s/risingwave-0.19.0/target`

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/risingwavelabs/homebrew-risingwave/issues

Error: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences.

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.2.1.

**Comment by BugenZhao** [comment]
I cannot reproduce this issue locally. Have you previously configured Rust/Cargo environment for development as well? If so, would you please check whether there're any global overrides of cargo config or `rustflags`?

**Comment by BugenZhao** [comment]
UPDATE:

After upgrading `brew` to the latest version and running it on an x86 Mac, I've successfully reproduced this issue. Seems related to an "optimization" introduced by Homebrew several days ago. (https://github.com/Homebrew/brew/pull/15544)

**Comment by WZRPW** [comment]
No problem now.
